#!/bin/bash

if [ "${HOSTNAME}" = dc1proseldap03 ];
then
   CURRENT_DIR=${PWD}
   
   echo "Freshen things up..."
   cd /home/lowk
   tar -cpf - bin | ssh cdlproseldap01 "tar -xpf - -C /home/lowk"
   cd /home/lowk/cases
   tar -cpf - TEMPLATE | ssh cdlproseldap01 "tar -xpf - -C /home/lowk/cases"
   
   cd ${CURRENT_DIR}
else
   echo "Only run ${0} from dc1proseldap03"
   exit
fi
